language: php

php:
  - "7.2"
  - "7.3"
  - "7.4snapshot"

cache:
  directories:
    - $HOME/.composer/cache

install:
  - composer install --no-interaction

script:
  - ./vendor/bin/phpunit --coverage-clover=coverage.xml

after_success:
  - bash <(curl -s https://codecov.io/bash)
